### ISSUE TITLE
Could not find/open device

### ISSUE THREAD

**Issue by hipitihop** [respeaker/mic_array_dfu#1]
On Ubuntu 16.04 running ./dfu I get "Could not find/open device" however lsusb shows:
```
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 006 Device 002: ID 2341:8036 Arduino SA Leonardo (CDC ACM, HID)
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 002: ID 05ca:18a1 Ricoh Co., Ltd 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub```

Any suggestions?

**Comment by xiongyihui** [comment]
The `dfu` is for the mic array, not for the respeaker core.

**Comment by hipitihop** [comment]
@xiongyihui Thanks for the response. I have the core + the mic array in the re-speaker case, is there a different procedure I should be following ?

**Comment by xiongyihui** [comment]
@hipitihop Just need to separate the core and the mic array and only connect the mic array with your computer, then use the `dfu` tool.

**Comment by mim** [comment]
I was getting this error until I ran `dfu` as root via sudo (on ubuntu 16.04.2)

**Comment by hipitihop** [comment]
@xiongyihui Thanks, that worked. closing
