### ISSUE TITLE
LIBUSB_ERROR_BUSY error on Linux Mint

### ISSUE THREAD

**Issue by hamishfagg** [respeaker/mic_array_dfu#4]
Using this tool does not work on my linux install, it fails with `LIBUSB_ERROR_BUSY`.

It can be fixed by adding a call to `libusb_detach_kernel_driver()` but I don't know enough about libUSB to make a PR.

**Comment by xiongyihui** [comment]
Hello @IVData 
It would be helpful if you could tell where to add the `libusb_detach_kernel_driver()`

**Comment by hamishfagg** [comment]
Probably around line 397 in xmosdfu.c. I don't know the side-effects of doing this though.

**Comment by xiongyihui** [comment]
just added it at https://github.com/respeaker/mic_array_dfu/blob/master/src/xmosdfu.c#L101
