### ISSUE TITLE
Lastest firmware different from original one

### ISSUE THREAD

**Issue by osmadja** [respeaker/mic_array_dfu#7]
Hello,
I received my ReSpeaker mic array and it was working with led ring being activated correctly depending on the direction of the voice without programming nothing (just plugging the mic in USB). 
Then I updated the firmware, as described in this repository. The upgrade worked and the mic still work but now the led ring does not activate in "stand alone mode", it only activates when running the python examples.

Is there a way to install the original firmware that came on the unit when I received it ?

Thanks,

**Comment by xiongyihui** [comment]
You can find it at https://github.com/respeaker/ReSpeaker_Microphone_Array_Firmware

**Comment by osmadja** [comment]
Hi Yihui,

Thanks for the quick answer. I tested with ReSpeaker_Microphone_Array_Firmware/xvsm/ReSpeaker_Mic_Array_firmware_factory.bin and could get the same behavior than original firmware.

Thanks!
